INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Luke', 'Skywalker', '19 BBY', '1951-03-25', 'luke@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Leia', 'Organa', '19 BBY', '1951-03-25', 'leia@rebelalliance.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Han', 'Solo', '29 BBY', '1941-04-29', 'han@smuggler.net');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Darth', 'Vader', '41.9 BBY', '1930-01-01', 'vader@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Yoda', 'Master', '896 BBY', '896-02-11', 'yoda@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Obi-Wan', 'Kenobi', '57 BBY', '1977-08-19', 'obiwan@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Palpatine', 'Sidious', '84 BBY', '1937-12-20', 'palpatine@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Chewbacca', 'Chewie', '200 BBY', '180-05-19', 'chewie@wookiee.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Padmé', 'Amidala', '46 BBY', '1967-05-12', 'padme@naboo.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Lando', 'Calrissian', '31 BBY', '1944-09-06', 'lando@cloudcity.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Anakin', 'Skywalker', '41.9 BBY', '1930-01-01', 'anakin@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Mace', 'Windu', '72 BBY', '1951-08-19', 'mace@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Boba', 'Fett', '31.5 BBY', '1948-03-28', 'boba@bountyhunter.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('R2-D2', 'Droid', 'Before 32 BBY', '2023-03-03', 'r2d2@droid.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('C-3PO', 'Droid', 'Before 32 BBY', '2023-10-06', 'c3po@droid.com');