INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Luke', 'Skywalker', '19 BBY', '1951-03-25', 'luke@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Leia', 'Organa', '19 BBY', '1951-03-25', 'leia@rebelalliance.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Han', 'Solo', '29 BBY', '1941-04-29', 'han@smuggler.net');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Darth', 'Vader', '41.9 BBY', '1930-01-01', 'vader@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Yoda', 'Master', '896 BBY', '896-02-11', 'yoda@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Obi-Wan', 'Kenobi', '57 BBY', '1977-08-19', 'obiwan@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Palpatine', 'Sidious', '84 BBY', '1937-12-20', 'palpatine@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Chewbacca', 'Chewie', '200 BBY', '180-05-19', 'chewie@wookiee.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Padmé', 'Amidala', '46 BBY', '1967-05-12', 'padme@naboo.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Lando', 'Calrissian', '31 BBY', '1944-09-06', 'lando@cloudcity.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Anakin', 'Skywalker', '41.9 BBY', '1930-01-01', 'anakin@sithempire.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Mace', 'Windu', '72 BBY', '1951-08-19', 'mace@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Boba', 'Fett', '31.5 BBY', '1948-03-28', 'boba@bountyhunter.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('R2-D2', 'Droid', 'Before 32 BBY', '2023-03-03', 'r2d2@droid.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('C-3PO', 'Droid', 'Before 32 BBY', '2023-10-06', 'c3po@droid.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Rey', 'Skywalker', 'Unknown', '2025-02-10', 'rey@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Finn', 'Stormtrooper', 'Unknown', '2025-03-15', 'finn@resistance.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Kylo', 'Ren', '5 ABY', '2019-12-20', 'kylo@firstorder.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Poe', 'Dameron', 'Unknown', '2024-07-05', 'poe@resistance.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Hera', 'Syndulla', 'Unknown', '2022-06-30', 'hera@rebels.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Qui-Gon', 'Jinn', 'Unknown', '1999-05-19', 'qui-gon.jinn@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Aayla', 'Secura', '48 BBY', '1977-05-25', 'aayla.secura@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Kit', 'Fisto', 'Unknown', '2005-03-15', 'kit.fisto@jedi.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Asajj', 'Ventress', 'Unknown', '2003-12-20', 'asajj.ventress@sith.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Grievous', 'Cyborg', 'Unknown', '2008-07-05', 'grievous@separatists.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Jango', 'Fett', 'Unknown', '2002-06-30', 'jango.fett@bountyhunter.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Aurra', 'Sing', 'Unknown', '2002-06-30', 'aurra.sing@bountyhunter.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Cad', 'Bane', 'Unknown', '2008-06-13', 'cad.bane@bountyhunter.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Hondo', 'Ohnaka', 'Unknown', '2008-06-13', 'hondo.ohnaka@pirate.com');
INSERT INTO Customers (name, surname, birth_date, created_at, email) VALUES ('Emperor', 'Sith', 'Unknown', '1977-05-25', 'emperor@sithempire.com');
